services:
  db-products:
    image: postgres:15
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: nextcart_admin
      POSTGRES_PASSWORD: localpassword
    ports:
      - "5434:5432"
    volumes:
      - products_data:/var/lib/postgresql/data

  api:
    build: .
    entrypoint: python
    command: -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      LOCAL_DB_HOST: db-products
      LOCAL_DB_PORT: "5432"
      LOCAL_DB_PASSWORD: localpassword
    depends_on:
      - db-products
    volumes:
      - .:/var/task  # hot reload

volumes:
  products_data:
